version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TestTask
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TestTaskDb
      SPRING_DATASOURCE_USERNAME: Timur
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: Timur
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TestTaskDb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
