#version: '3.9'
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: TestTask
#    ports:
#      - "${SERVER_PORT:-8080}:8080"
#    env_file:
#      - .env
#    depends_on:
#      - db
#
#  db:
#    image: postgres:15-alpine
#    container_name: postgres_db
#    ports:
#      - "5433:5432"
#    env_file:
#      - .env
#    volumes:
#      - db_data:/var/lib/postgresql/data
#      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#
#volumes:
#  db_data:
version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TestTask
    ports:
      - "${SERVER_PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
