server:
  port: 8080
  address: localhost
spring:
  application:
    name: Polyclinic_PetProject
  datasource:
    url: jdbc:postgresql://localhost:5432/TestTaskDb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true