#
#server:
#  port: ${SERVER_PORT:8080}
#  address: 0.0.0.0
#spring:
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:local}
#  application:
#    name: TestTask
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/TestTaskDb}
#    driver-class-name: org.postgresql.Driver
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:admin}
#  jpa:
#    show-sql: ${SPRING_JPA_SHOW_SQL:true}
#    generate-ddl: true
#    hibernate:
#      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
#    open-in-view: true
#    properties:
#      hibernate:
#        connection:
#          isolation: 8
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    enabled: true
server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # Профиль по умолчанию - local
  application:
    name: TestTask
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/TestTaskDb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    generate-ddl: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    open-in-view: true
    properties:
      hibernate:
        connection:
          isolation: 8
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/TestTaskDb
    username: Timur
    password: admin

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/TestTaskDb
    username: postgres
    password: admin

